version: v0.1
name: classifier

classifier:
  criterion:
    name: wbce
    class_weight: output/weights_14.csv
    device: cpu
  metric: 
    name: "auc"
    binary: True
    classes: "data/vinbigdata/vin_classes_14.npy"
  optimizer: 
    name: adam
    lr: 1.e-4
  scheduler:
    name: reduce_plateu
  callbacks: [ { "name": "report_to_wandb" }, {"name": "early_stopping", "monitor": "eval_loss"}, {"name": "warm_restart"} ]

    